# .scrutinizer.yml
filter:
    excluded_paths:
        - assets/*
build:
    environment:
        php:
            version: 5.4.41       # Common versions: 5.4, 5.5, 5.6 or hhvm
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["admin/*", "class/*", "include/*", "language/*", "templates/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["assets", "docs", "sql", "language", "templates"]
    php_loc:
        enabled: true
        excluded_dirs: ["assets", "docs", "sql", "language", "templates"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["assets", "docs", "sql", "language", "templates"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["admin/*", "class/*", "include/*", "language/*"]
    sensiolabs_security_checker: true
