language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer self-update
install:
  - composer --working-dir=htdocs/xoops_lib/ install

before_script:
  - mysql -e 'create database'

script:
  - jquery
  - bootstrap

after_script:
  - 
